deploymentMode: SingleBinary
loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  storage:
    type: filesystem
  schemaConfig:
    configs:
      - from: "2024-01-01"
        store: tsdb
        object_store: filesystem
        schema: v13
        index:
          prefix: loki_index_
          period: 24h
  limits_config:
    retention_period: 720h
  compactor:
    retention_enabled: true
    delete_request_store: filesystem
  rulerConfig:
    storage:
      type: local
      local:
        directory: /rules
    rule_path: /tmp/loki-ruler
    alertmanager_url: http://alertmanager.logging.svc.cluster.local:9093
    enable_alertmanager_v2: true
    evaluation_interval: 1m
    poll_interval: 1m
singleBinary:
  replicas: 1
  persistence:
    enabled: true
    size: 20Gi
    storageClass: local-path
  extraVolumes:
    - name: loki-rules
      configMap:
        name: loki-alerting-rules
  extraVolumeMounts:
    - name: loki-rules
      mountPath: /rules/fake
read: {replicas: 0}
write: {replicas: 0}
backend: {replicas: 0}
chunksCache: {enabled: false}
resultsCache: {enabled: false}
gateway: {enabled: false}
lokiCanary: {enabled: false}
test: {enabled: false}
monitoring: {selfMonitoring: {enabled: false, grafanaAgent: {installOperator: false}}}
